window.env = {
  "ACLOCAL_PATH": "C:\\Program Files\\Git\\mingw64\\share\\aclocal;C:\\Program Files\\Git\\usr\\share\\aclocal",
  "ALLUSERSPROFILE": "C:\\ProgramData",
  "APPDATA": "C:\\Users\\Befous\\AppData\\Roaming",
  "ChocolateyInstall": "C:\\ProgramData\\chocolatey",
  "ChocolateyLastPathUpdate": "133444891846520201",
  "ChocolateyToolsLocation": "C:\\tools",
  "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\crashpad_20372_JZJSPCGBAQISFRZS",
  "COLOR": "1",
  "COLORTERM": "truecolor",
  "COMMONPROGRAMFILES": "C:\\Program Files\\Common Files",
  "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
  "CommonProgramW6432": "C:\\Program Files\\Common Files",
  "COMPUTERNAME": "LAPTOP-QGLD5OL1",
  "COMSPEC": "C:\\WINDOWS\\system32\\cmd.exe",
  "CONFIG_SITE": "C:/Program Files/Git/etc/config.site",
  "DISPLAY": "needs-to-be-defined",
  "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
  "EDITOR": "C:\\WINDOWS\\notepad.exe",
  "EFC_8780": "1",
  "EXEPATH": "C:\\Program Files\\Git\\bin",
  "GIT_ASKPASS": "c:\\Users\\Befous\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh",
  "GOPATH": "C:\\Users\\Befous\\go",
  "GOPROXY": "proxy.golang.org",
  "HOME": "C:\\Users\\Befous",
  "HOMEDRIVE": "C:",
  "HOMEPATH": "\\Users\\Befous",
  "HOSTNAME": "LAPTOP-QGLD5OL1",
  "IGCCSVC_DB": "AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAvRFz89lnR0iJ4ZZP9LQNggQAAAACAAAAAAAQZgAAAAEAACAAAAA4rPf1hRD4iBT1boH0a3DbKOyo2GFuojHjIte5h6lCmQAAAAAOgAAAAAIAACAAAAADkRhnS9jSdhVOF9TmmrMALSsKBua02U3WFRva4dzioWAAAACFeyNAsGRmgAuSe2Kb1x8kv6ZOb7iBID2oY5w8i/Lp8W9N0uLWyYHPC/AUnPGTXsl5lV81UkIR0pKYrvzufR1RIWzss/F2xTXBgP6Cfth1okPvs+7mYBQQPHhejUrJlnVAAAAAJX7wr6QdGA5N3CGdhYRb+1sfRL8pM29gP1MwP+3o1SmKll8YiVmxw8mBNWIFqyuB+EvKywNIMXUipqN4aTk0Qg==",
  "INFOPATH": "C:\\Program Files\\Git\\mingw64\\local\\info;C:\\Program Files\\Git\\mingw64\\share\\info;C:\\Program Files\\Git\\usr\\local\\info;C:\\Program Files\\Git\\usr\\share\\info;C:\\Program Files\\Git\\usr\\info;C:\\Program Files\\Git\\share\\info",
  "INIT_CWD": "C:\\Users\\Befous\\Desktop\\Tugas\\Semester 5\\Proyek 3\\PhilanderNews\\Github\\frondend\\cobareact",
  "INTEL_DEV_REDIST": "C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\",
  "LANG": "en_US.UTF-8",
  "LOCALAPPDATA": "C:\\Users\\Befous\\AppData\\Local",
  "LOGONSERVER": "\\\\LAPTOP-QGLD5OL1",
  "MANPATH": "C:\\Program Files\\Git\\mingw64\\local\\man;C:\\Program Files\\Git\\mingw64\\share\\man;C:\\Program Files\\Git\\usr\\local\\man;C:\\Program Files\\Git\\usr\\share\\man;C:\\Program Files\\Git\\usr\\man;C:\\Program Files\\Git\\share\\man",
  "MIC_LD_LIBRARY_PATH": "C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\compiler\\lib\\mic",
  "MINGW_CHOST": "x86_64-w64-mingw32",
  "MINGW_PACKAGE_PREFIX": "mingw-w64-x86_64",
  "MINGW_PREFIX": "C:/Program Files/Git/mingw64",
  "MONGOCONNSTRINGENV": "mongodb+srv://befous:yUft6BXdcZJ647e8@cluster0.sstnspm.mongodb.net/",
  "MSYSTEM": "MINGW64",
  "MSYSTEM_CARCH": "x86_64",
  "MSYSTEM_CHOST": "x86_64-w64-mingw32",
  "MSYSTEM_PREFIX": "C:/Program Files/Git/mingw64",
  "NODE": "C:\\Program Files\\nodejs\\node.exe",
  "NODE_EXE": "C:\\Program Files\\nodejs\\\\node.exe",
  "NPM_CLI_JS": "C:\\Program Files\\nodejs\\\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_command": "run-script",
  "npm_config_cache": "C:\\Users\\Befous\\AppData\\Local\\npm-cache",
  "npm_config_globalconfig": "C:\\Users\\Befous\\AppData\\Roaming\\npm\\etc\\npmrc",
  "npm_config_global_prefix": "C:\\Users\\Befous\\AppData\\Roaming\\npm",
  "npm_config_init_module": "C:\\Users\\Befous\\.npm-init.js",
  "npm_config_local_prefix": "C:\\Users\\Befous\\Desktop\\Tugas\\Semester 5\\Proyek 3\\PhilanderNews\\Github\\frondend\\cobareact",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "npm_config_node_gyp": "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
  "npm_config_noproxy": "",
  "npm_config_prefix": "C:\\Users\\Befous\\AppData\\Roaming\\npm",
  "npm_config_userconfig": "C:\\Users\\Befous\\.npmrc",
  "npm_config_user_agent": "npm/9.5.0 node/v18.14.2 win32 x64 workspaces/false",
  "npm_execpath": "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_lifecycle_event": "build",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "npm_node_execpath": "C:\\Program Files\\nodejs\\node.exe",
  "npm_package_json": "C:\\Users\\Befous\\Desktop\\Tugas\\Semester 5\\Proyek 3\\PhilanderNews\\Github\\frondend\\cobareact\\package.json",
  "npm_package_name": "cobareact",
  "npm_package_version": "0.1.0",
  "NPM_PREFIX_NPM_CLI_JS": "C:\\Users\\Befous\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "NUMBER_OF_PROCESSORS": "16",
  "OneDrive": "C:\\Users\\Befous\\OneDrive",
  "OneDriveConsumer": "C:\\Users\\Befous\\OneDrive",
  "OnlineServices": "Online Services",
  "ORIGINAL_PATH": "C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\Befous\\bin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64\\compiler;C:\\Program Files\\Python311\\Scripts;C:\\Program Files\\Python311;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0;C:\\windows\\System32\\OpenSSH;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\dotnet;C:\\Users\\Befous\\AppData\\Roaming\\Python\\Python311\\Scripts;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\nodejs;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Go\\bin;C:\\Users\\Befous\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Befous\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\Befous\\AppData\\Roaming\\Python\\Python311\\Scripts;C:\\Users\\Befous\\AppData\\Roaming\\npm;C:\\Users\\Befous\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\Befous\\.dotnet\\tools;C:\\Program Files\\heroku\\bin;C:\\Users\\Befous\\go\\bin;C:\\Users\\Befous\\AppData\\Local\\Pub\\Cache\\bin;C:\\src\\flutter\\bin;C:\\src\\flutter\\bin\\cache\\dart-sdk\\bin",
  "ORIGINAL_TEMP": "C:/Users/Befous/AppData/Local/Temp",
  "ORIGINAL_TMP": "C:/Users/Befous/AppData/Local/Temp",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "OS": "Windows_NT",
  "PATH": "C:\\Users\\Befous\\Desktop\\Tugas\\Semester 5\\Proyek 3\\PhilanderNews\\Github\\frondend\\cobareact\\node_modules\\.bin;C:\\Users\\Befous\\Desktop\\Tugas\\Semester 5\\Proyek 3\\PhilanderNews\\Github\\frondend\\node_modules\\.bin;C:\\Users\\Befous\\Desktop\\Tugas\\Semester 5\\Proyek 3\\PhilanderNews\\Github\\node_modules\\.bin;C:\\Users\\Befous\\Desktop\\Tugas\\Semester 5\\Proyek 3\\PhilanderNews\\node_modules\\.bin;C:\\Users\\Befous\\Desktop\\Tugas\\Semester 5\\Proyek 3\\node_modules\\.bin;C:\\Users\\Befous\\Desktop\\Tugas\\Semester 5\\node_modules\\.bin;C:\\Users\\Befous\\Desktop\\Tugas\\node_modules\\.bin;C:\\Users\\Befous\\Desktop\\node_modules\\.bin;C:\\Users\\Befous\\node_modules\\.bin;C:\\Users\\node_modules\\.bin;C:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Users\\Befous\\Desktop\\Tugas\\Semester 5\\Proyek 3\\PhilanderNews\\Github\\frondend\\cobareact\\node_modules\\.bin;C:\\Users\\Befous\\Desktop\\Tugas\\Semester 5\\Proyek 3\\PhilanderNews\\Github\\frondend\\node_modules\\.bin;C:\\Users\\Befous\\Desktop\\Tugas\\Semester 5\\Proyek 3\\PhilanderNews\\Github\\node_modules\\.bin;C:\\Users\\Befous\\Desktop\\Tugas\\Semester 5\\Proyek 3\\PhilanderNews\\node_modules\\.bin;C:\\Users\\Befous\\Desktop\\Tugas\\Semester 5\\Proyek 3\\node_modules\\.bin;C:\\Users\\Befous\\Desktop\\Tugas\\Semester 5\\node_modules\\.bin;C:\\Users\\Befous\\Desktop\\Tugas\\node_modules\\.bin;C:\\Users\\Befous\\Desktop\\node_modules\\.bin;C:\\Users\\Befous\\node_modules\\.bin;C:\\Users\\node_modules\\.bin;C:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Users\\Befous\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\local\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\Befous\\bin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64\\compiler;C:\\Program Files\\Python311\\Scripts;C:\\Program Files\\Python311;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0;C:\\windows\\System32\\OpenSSH;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\dotnet;C:\\Users\\Befous\\AppData\\Roaming\\Python\\Python311\\Scripts;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\nodejs;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Go\\bin;C:\\Users\\Befous\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Befous\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\Befous\\AppData\\Roaming\\Python\\Python311\\Scripts;C:\\Users\\Befous\\AppData\\Roaming\\npm;C:\\Users\\Befous\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\Befous\\.dotnet\\tools;C:\\Program Files\\heroku\\bin;C:\\Users\\Befous\\go\\bin;C:\\Users\\Befous\\AppData\\Local\\Pub\\Cache\\bin;C:\\src\\flutter\\bin;C:\\src\\flutter\\bin\\cache\\dart-sdk\\bin;C:\\Program Files\\Git\\usr\\bin\\vendor_perl;C:\\Program Files\\Git\\usr\\bin\\core_perl",
  "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW",
  "PKG_CONFIG_PATH": "C:\\Program Files\\Git\\mingw64\\lib\\pkgconfig;C:\\Program Files\\Git\\mingw64\\share\\pkgconfig",
  "PKG_CONFIG_SYSTEM_INCLUDE_PATH": "C:/Program Files/Git/mingw64/include",
  "PKG_CONFIG_SYSTEM_LIBRARY_PATH": "C:/Program Files/Git/mingw64/lib",
  "platformcode": "M7",
  "PLINK_PROTOCOL": "ssh",
  "PROCESSOR_ARCHITECTURE": "AMD64",
  "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 154 Stepping 3, GenuineIntel",
  "PROCESSOR_LEVEL": "6",
  "PROCESSOR_REVISION": "9a03",
  "ProgramData": "C:\\ProgramData",
  "PROGRAMFILES": "C:\\Program Files",
  "ProgramFiles(x86)": "C:\\Program Files (x86)",
  "ProgramW6432": "C:\\Program Files",
  "PROMPT": "$P$G",
  "PSModulePath": "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules",
  "PUBLIC": "C:\\Users\\Public",
  "PWD": "C:/Users/Befous/Desktop/Tugas/Semester 5/Proyek 3/PhilanderNews/Github/frondend/cobareact",
  "REACT_APP_LOL": "ASD",
  "RegionCode": "APJ",
  "SESSIONNAME": "Console",
  "SHELL": "C:\\Program Files\\Git\\usr\\bin\\bash.exe",
  "SHLVL": "2",
  "SSH_ASKPASS": "C:/Program Files/Git/mingw64/bin/git-askpass.exe",
  "SYSTEMDRIVE": "C:",
  "SYSTEMROOT": "C:\\WINDOWS",
  "TEMP": "C:\\Users\\Befous\\AppData\\Local\\Temp",
  "TERM": "xterm-256color",
  "TERM_PROGRAM": "vscode",
  "TERM_PROGRAM_VERSION": "1.84.2",
  "TMP": "C:\\Users\\Befous\\AppData\\Local\\Temp",
  "TMPDIR": "C:\\Users\\Befous\\AppData\\Local\\Temp",
  "USERDOMAIN": "LAPTOP-QGLD5OL1",
  "USERDOMAIN_ROAMINGPROFILE": "LAPTOP-QGLD5OL1",
  "USERNAME": "Befous",
  "USERPROFILE": "C:\\Users\\Befous",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
  "VSCODE_GIT_ASKPASS_MAIN": "c:\\Users\\Befous\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
  "VSCODE_GIT_ASKPASS_NODE": "C:\\Users\\Befous\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
  "VSCODE_GIT_IPC_HANDLE": "\\\\.\\pipe\\vscode-git-96030ea173-sock",
  "WINDIR": "C:\\WINDOWS",
  "ZES_ENABLE_SYSMAN": "1",
  "_": "C:/Program Files/nodejs/node.exe"
};